# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

# Labels for action/labeler

area/kubernetes:
  - kubernetes/*
  - kubernetes/**/*

area/gcp:
  - iac/gcp/*
  - iac/gcp/**/*

area/aws:
  - iac/aws/*
  - iac/aws/**/*

area/azure:
  - iac/azure/*
  - iac/azure/**/*

kind/documentation:
  - docs/*
  - docs/**/*
